name: CI/CD Pipeline

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    
    steps: 
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc[all] pytest mlflow
      
      #DVC Pull
      - name: DVC Pull
        run: dvc pull

      # Run unit tests
      - name: Run tests
        run: pytest -q 
      
      # Build docker image
      - name: Build Docker image
        run: docker build -t ml-api .

      # Push Docker image to registry
      - name: Push Docker image
        uses: docker/build-push-actions@v4
        with: 
          push: true
          tags: ghcr.io/${{ github.repository }}/mlops-api:latest
    